#!/usr/bin/env bash

if [ ! -f install ]; then
    echo 'install must be run within its container folder' 1>&2
    exit 1
fi

CURDIR=`pwd`
OLDGOPATH="$GOPATH"
export GOPATH="$CURDIR"

export GOPATH="$OLDGOPATH"
#export CC=/usr/local/bin/gcc-4.9
 go install datacount



echo 'finished'

